apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service2-virtual
spec:
  hosts:
    - service2 # ім'я Service до якого застосовується налаштування
  http:
    - route:
        - destination:
            host: service2 # ім'я Service до якого застосовується налаштування
      timeout: 2s
      retries:
        attempts: 2
        retryOn: 5xx
        perTryTimeout: 5s